### ISSUE TITLE
[1.12] Crash, old rf api

### ISSUE THREAD

**Issue by Austin5003** [vpzomtrrfrt/JAPTA#10]
[crash-2017-11-25_23.31.02-client.txt](https://github.com/vpzomtrrfrt/JAPTA/files/1503633/crash-2017-11-25_23.31.02-client.txt)

**Comment by vpzomtrrfrt** [comment]
Yup, fixing now

**Comment by vpzomtrrfrt** [comment]
Is RF support important, or should I scrap it?

**Comment by vpzomtrrfrt** [comment]
I've removed the old API in v1.11.11, Tesla and Forge Energy are still supported.
