### ISSUE TITLE
[Suggestion] Make the RNG Quarry use the enchantments of Tinker Tools

### ISSUE THREAD

**Issue by BraynStorm** [vpzomtrrfrt/JAPTA#3]
1. It destroys tools if they hit 0 durability.
2. It doesn't respect the tool's enchantements / modifiers.

Keep up the good work.

**Comment by vpzomtrrfrt** [comment]
Okay, should be better in 1.4.1.  Tell me if it worked.

**Comment by BraynStorm** [comment]
Much better. Thanks a lot.
