### ISSUE TITLE
Book via Guide API

### ISSUE THREAD

**Issue by Dragnier** [vpzomtrrfrt/JAPTA#5]
Found a couple of issues; the first being a recipe conflict.

![2016-06-18_18 56 47](https://cloud.githubusercontent.com/assets/19270499/16174227/5bb36d3e-3587-11e6-8ee0-d7bc0b60469b.png)

The second being an issue with one book listing displaying improperly.

![2016-06-18_18 58 28](https://cloud.githubusercontent.com/assets/19270499/16174229/80f8ac44-3587-11e6-9494-94b3c32f7551.png)

**Comment by vpzomtrrfrt** [comment]
Should be fixed in the next version
