### ISSUE TITLE
Allow Heat Converter to work on other furnace faces

### ISSUE THREAD

**Issue by Yowesephth** [vpzomtrrfrt/JAPTA#6]
It strikes me as odd that the heat converter can only work on top of a furnace. This makes it impossible to move rf from it using the mod's very own flux hopper. I don't know if this was the intention or not, but it sticks out to me as strange.

**Comment by vpzomtrrfrt** [comment]
OK, will work on all faces in the next update.  Not sure exactly when that'll happen.

**Comment by vpzomtrrfrt** [comment]
Done in v1.11.0
