### ISSUE TITLE
Crash when charging RF potato in a chest connected to chest charger

### ISSUE THREAD

**Issue by Yowesephth** [vpzomtrrfrt/JAPTA#7]
http://paste.ee/p/0POdd

**Comment by vpzomtrrfrt** [comment]
:(

I have an idea of how to fix this, I'll try later today

**Comment by vpzomtrrfrt** [comment]
Should be fixed as of v1.10.2

**Comment by Yowesephth** [comment]
Tried the update, seems to work just fine now!
