### ISSUE TITLE
[1.11] All the bugs

### ISSUE THREAD

**Issue by alothmanmoe** [vpzomtrrfrt/JAPTA#8]
Hello whoever is reading this,
iv run into a few bugs while using this mod in minecraft 1.11
So I'm working on my own tech mod in 1.11 and need a way to generate power as of right now, and this mod is the only current updating one for 1.11 so i said id give it a try, adding it to my dev workspace and  using *some* of the stuff in game works. The stuff that doesn't work however is all the TileEntities, they just crash my game when i place any down, now i do realize that 1.11 is heavily under development but the upload date of the 1.11 file shows that it has not been updated the the latest 1.11 builds from yesterday or so, which now fixes modded TE's.
Sorry for the long (unneeded) explanation, just basically informing you that the mod needs a forge update and TE's to be fixed.

**Comment by vpzomtrrfrt** [comment]
Which version of forge are you using?  Looks fine in 1.11-13.19.0.2153, though I haven't tried adding it to a dev environment.  Which block are you placing?

**Comment by vpzomtrrfrt** [comment]
Do you have the crash log?

**Comment by alothmanmoe** [comment]
I am trying to place any block that can be used to generate RF, im on forge 13.19.0.2148 atm until i update

**Comment by vpzomtrrfrt** [comment]
Maybe that version of forge is broken?  I'm placing the Cake Converter right now with no problems.

**Comment by alothmanmoe** [comment]
Lemme grab a crash log just 1 sec

**Comment by alothmanmoe** [comment]
http://pastebin.com/RBzMFZb6

**Comment by vpzomtrrfrt** [comment]
Just tried in a dev environment, got the same error.  I'll see what I can find out about it.

**Comment by vpzomtrrfrt** [comment]
I'm really confused. field_145850_b is TileEntity.world, so why is it missing?

**Comment by alothmanmoe** [comment]
if (((ItemStack)this.pulverizerInv.get(0)).func_190926_b()) {
        return false;
        }else {
            return true;
        }
im using func_190926_b to check if the slot is null and return false and if it has an item in it then return true

**Comment by vpzomtrrfrt** [comment]
OK, try v1.11.4, building now

**Comment by alothmanmoe** [comment]
Ty, works just fine now :D
